# pyproject.toml (minimal example)
[build-system]
requires = ['setuptools>=68', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = 'example_package'
version = '0.1.0'
requires-python = '>=3.10'
dependencies = []

[tool.setuptools.packages.find]
where = ['src']
